enyo.depends(
  "gui.js",
  "logo.js",
  "workspace_toolbar.js",
  "status_bar.js",
  "user_nav.js",
  "extension_selector.js",
  "extension_sub_list.js",
  "workspace.js",
  "model_view.js",
	"search.js",
	"widgets",
	"partials",
	"helpers"
);
